# Site settings
title: Francis J. DiTraglia
email: fditra@sas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  Should put my contact details here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fjditr
github_username:  fditraglia

# Build settings
markdown: kramdown
